### ISSUE TITLE
Error: instrumentationKey value cannot be null

### ISSUE THREAD

**Issue by lalekov** [vuder/AzureCostAnomalyDetector#15]
When I try to run code I get following Error:
[Error] Executed 'AzureCostAnomalyDetector' (Failed, Id=*** Duration=8ms)Value cannot be null. (Parameter 'instrumentationKey')

AzureCostAnomalyDetector-AppInsightsInstrumentationKey parameter is set and I tried with multiple different Application Insights.

**Comment by vuder** [comment]
try to set the variable with '.' instead of '-' 
for example AzureCostAnomalyDetector.AppInsightsInstrumentationKey

When KeyVault is source of configuration then hyphen is needed in name of the key in KeyVault

**Comment by lalekov** [comment]
Yes, that resolved this error. Thank you for help.
